### ISSUE TITLE
How do I disable RSS display in my blog?

### ISSUE THREAD

**Issue by zevorn** [clente/hugo-bearcub#16]
How do I disable RSS display in my blog?
![image](https://github.com/clente/hugo-bearcub/assets/62325246/507b473f-4951-4da1-a0d7-18f2e68c4be0)

**Comment by clente** [comment]
You need to delete this line: https://github.com/clente/hugo-bearcub/blob/main/layouts/partials/nav.html#L4

**Comment by BennyDeeDev** [comment]
I created a fork without RSS for anyone that is interested: https://github.com/BennyDeeDev/hugo-bearcub
