### ISSUE TITLE
RSS link broken (in demo site at least)

### ISSUE THREAD

**Issue by NeatNit** [clente/hugo-bearcub#2]
In the [demo site](https://clente.github.io/hugo-bearcub/), the RSS link in the navbar links to https://clente.github.io/blog/index.xml which is 404. It should instead link to https://clente.github.io/hugo-bearcub/index.xml (`hugo-bearcub` instead of `blog`).

I've got no idea if this bug is in the theme or just the demo site, I've only heard of Hugo yesterday and this theme caught my eye ᕦʕ •ᴥ•ʔᕤ

**Comment by clente** [comment]
Sorry it took me such a long time to get to your issue... For some weird reason I wasn't watching my own repo 😅

You're absolutely right, there is something wrong with the RSS link. Thank you for pointing it out! A fix should be coming soon.
