### ISSUE TITLE
How do I add a new non-blog page?

### ISSUE THREAD

**Issue by yuki-was-taken** [clente/hugo-bearcub#20]
I want to add a new page to my website to display links to my social media and more, but when i make a new directory `content/links/` and click the link on the nav-bar, it shows this instead of my stuff:

![20240627_18h27m53s_grim](https://github.com/clente/hugo-bearcub/assets/141553384/d136572d-a2b0-472a-be66-07fa9942f2de)

How do I make the page not a blog post page?

**Comment by clente** [comment]
You should create a `links.md` file inside `content/` with a front matter like this:

```
---
title: "Links"
menu: "main"
weight: 2
---
```
