### ISSUE TITLE
Multiple h1 tags on page

### ISSUE THREAD

**Issue by handmeatowel** [clente/hugo-bearcub#24]
This isn't as much a bear cub thing as much as it is HTML/CSS thing that bear cub uses: Currently the page title and the website/blog title is formatted with h1. 
I believe it's considered a bad practice to use multiple h1 tags [outside of separate section tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section). Bear Blog makes the same mistake.

I was only able to give it little thought how to improve the accessibility situation further; wouldn't it be better to preserve the h1 tag for the actual content and format the page title with CSS? **_Or_**, perhaps even better, should we use a section tag for the header and another section tag for the content?

**Comment by clente** [comment]
This is a good point. However, since this theme is trying to replicate Bear Blog, I'm not sure it's worth it to fix this specific problem. Changing the HTML in this way might hinder backwards compatibility and that sort of stuff...

Thanks for the suggestion, though!
