### ISSUE TITLE
Customising the byline

### ISSUE THREAD

**Issue by Ian2020** [clente/hugo-bearcub#25]
Hi, this is a great theme thank you for making it!

I had reason to customise my **byline** to include the date a post was last updated and some other metadata. I've solved my problem by duplicating this theme's `single.html` into my `layouts` dir and making the necessary changes.

However this means I need to continue sync any subsequent changes in this repo to my duplicate. Would you be open to adding something like `{{- partial "custom_byline.html" . -}}` in the theme so I can just change the part I want? I can submit a PR for this change if you think it makes sense.

**Comment by clente** [comment]
Sure, you can open a PR with this change!
