### ISSUE TITLE
Unformatted Embed Description

### ISSUE THREAD

**Issue by EternalBlissed** [clente/hugo-bearcub#26]
Hi, Is there a way to fix the unformatted description or just remove it all together? 

![image](https://github.com/user-attachments/assets/89ebe6dc-cf8b-49b6-8f68-7c37f41f7fee)

**Comment by clente** [comment]
I'm unsure where this is coming from. I would need more information about the error and the original file to better understand the bug.

**Comment by VisruthSK** [comment]
Hi! I'm running into the same issue and was wondering how you resolved it @EternalBlissed.
