### ISSUE TITLE
Validation error with <content> tag 

### ISSUE THREAD

**Issue by bmp** [clente/hugo-bearcub#27]
Hello, thank you for making the them. When I try to validate the produced/generated HTML using https://validator.w3.org/nu/ I get the following error

```
Element content not allowed as child of element [main](https://html.spec.whatwg.org/multipage/#the-main-element) in this context. (Suppressing further errors from this subtree.)
```
The checker points me to https://html.spec.whatwg.org/multipage/#the-main-element and https://html.spec.whatwg.org/multipage/#flow-content-2 as possibilities, I tried modifying `<content>` to `<article>` and `<section>`, but started throwing up other validation errors then.

Could you please let me know what would be an appropriate change?

**Comment by clente** [comment]
Sorry, I can't help you with that. I'm not familiar with this validator.
