### ISSUE TITLE
Social card preview overlaps author name if the title is long

### ISSUE THREAD

**Issue by tupaschoal** [clente/hugo-bearcub#9]
When the title is relatively long, like in this blog post, the social card preview gets mangled, this is how it looks in Whatsapp and Discord:

![image](https://github.com/clente/hugo-bearcub/assets/6443427/be523b57-cb93-4b20-86d7-3fb84b68fdde)![image](https://github.com/clente/hugo-bearcub/assets/6443427/b35b9c64-0edd-4adb-9421-a365d34086a0)

The full title is `Catalyst Quality Award on the Cadence Innovation Conference`, you can see it is overlapping the author name.

A few considerations:

1. I know it's experimental, but I thought I'd report, let me know if you don't want to
2. In this post the first thing in the content is an image, but it doesn't become the image on the social card. Do I have to use the `featured_image` on the front matter for it to work?

PS: Thanks for doing this amazing theme :)

**Comment by clente** [comment]
Sorry for taking so long to get back to your issue. Regarding your points:

1. Thanks for reporting! I'll try to implement some way of dynamically reducing the font size in case the title is too long... Not sure if it'll work, but I'll give it a shot.
2. For an image to become the social card, you need to add it to `images` in the front matter. See: https://gohugo.io/content-management/front-matter/#predefined

**Comment by clente** [comment]
Would this work for you, @tupaschoal?

![social_card_bg_hu24b6b25ef60ca259d3d1b88ebbfdfb28_6698_56ced66c3de4ce5529aa94ca28b9fe55](https://github.com/clente/hugo-bearcub/assets/7017340/4156dcff-3717-40b4-b4c0-df263132e40c)
